version: '3'

services:
  registry:
    image: registry:2
    restart: always
    volumes:
      - ./registry_configuration.yml:/etc/docker/registry/config.yml
      - ./registry_data:/var/lib/registry
    ports:
      - 5000:5000
    depends_on:
      - redis

  jenkins:
    build: .
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
     - ./jenkins_data:/var/jenkins_home
